services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wirevault:${APP_VERSION:-local}
    environment:
      NODE_ENV: production
      DATABASE_URL: "file:/data/prod.db"
      UPLOAD_ROOT: "/data/uploads"
      SESSION_HMAC_SECRET: "${SESSION_HMAC_SECRET}"
      PIN_HASH_SALT_ROUNDS: "10"
      SESSION_TTL_MINUTES: "20"
      ADMIN_SEED_EMAIL: "${ADMIN_SEED_EMAIL:-admin@up2charge.be}"
      ADMIN_SEED_PASSWORD: "${ADMIN_SEED_PASSWORD:-ChangeMe123!}"
    volumes:
      - /data:/data
    restart: unless-stopped
    networks: [web]

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports: ["80:80","443:443"]
    environment:
      ACME_AGREE: "true"
      DOMAIN: "${DOMAIN}"
      EMAIL: "${EMAIL}"
    volumes:
      - /data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data/caddy
      - caddy-config:/config
    networks: [web]

volumes:
  caddy-data:
  caddy-config:

networks:
  web:
    driver: bridge
